### ISSUE TITLE
WB Year: Calculations wrong

### ISSUE THREAD

**Issue by pxlline** [pxlline/SwitzerlandTourism#8]
The workbook shows slightly higher values than the Quantum-Database.
Check RAW data.

**Comment by mirjamfrei** [comment]
Please use for ALL sheets using HESTA always the following filter: "Accommodation Type" = "Hotel" OR "Kurbetriebe

**Comment by pxlline** [comment]
Globaler Filter für Hotel und Kurbetriebe hinzugefügt

**Comment by pxlline** [comment]
Zudem: Forein Filter angepasst. Fehlende Länder ohne Schweiz hinzugefügt
